language: java
jdk:
 - openjdk14

sudo: false

notifications:
  email:
    recipients:
      - sergeykalenikov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always